export const themesList = [
  { value: "agents", label: "Agents" },
  { value: "agriculture", label: "Agriculture" },
  { value: "airplanes", label: "Airplanes" },
  { value: "aliens", label: "Aliens" },
  { value: "american football", label: "American Football" },
  { value: "ancient", label: "Ancient" },
  { value: "ancient china", label: "Ancient China" },
  { value: "ancient egypt", label: "Ancient Egypt" },
  { value: "androids", label: "Androids" },
  { value: "angels", label: "Angels" },
  { value: "animals", label: "Animals" },
  { value: "anime", label: "Anime" },
  { value: "ants", label: "Ants" },
  { value: "apocalypse", label: "Apocalypse" },
  { value: "archaeology", label: "Archaeology" },
  { value: "archery", label: "Archery" },
  { value: "art", label: "Art" },
  { value: "assassins", label: "Assassins" },
  { value: "asteroids", label: "Asteroids" },
  { value: "astronauts", label: "Astronauts" },
  { value: "athletics", label: "Athletics" },
  { value: "atlantis", label: "Atlantis" },
  { value: "aztecs", label: "Aztecs" },
  { value: "barbarians", label: "Barbarians" },
  { value: "bards", label: "Bards" },
  { value: "baseball", label: "Baseball" },
  { value: "basketball", label: "Basketball" },
  { value: "bicycle", label: "Bicycle" },
  { value: "billiards", label: "Billiards" },
  { value: "birds", label: "Birds" },
  { value: "books", label: "Books" },
  { value: "bounty hunter", label: "Bounty Hunter" },
  { value: "bowling", label: "Bowling" },
  { value: "boxing", label: "Boxing" },
  { value: "building blocks", label: "Building Blocks" },
  { value: "bunker", label: "Bunker" },
  { value: "cabs", label: "Cabs" },
  { value: "candy", label: "Candy" },
  { value: "cars", label: "Cars" },
  { value: "casinos", label: "Casinos" },
  { value: "castles", label: "Castles" },
  { value: "cats", label: "Cats" },
  { value: "chemistry", label: "Chemistry" },
  { value: "chess", label: "Chess" },
  { value: "chickens", label: "Chickens" },
  { value: "cinema", label: "Cinema" },
  { value: "circus", label: "Circus" },
  { value: "cities", label: "Cities" },
  { value: "civilizations", label: "Civilizations" },
  { value: "cleaning", label: "Cleaning" },
  { value: "climbing", label: "Climbing" },
  { value: "colonization", label: "Colonization" },
  { value: "comedy", label: "Comedy" },
  { value: "companies", label: "Companies" },
  { value: "conquest", label: "Conquest" },
  { value: "conspiracies", label: "Conspiracies" },
  { value: "contract killer", label: "Contract Killer" },
  { value: "cooking", label: "Cooking" },
  { value: "court case", label: "Court Case" },
  { value: "cowboys", label: "Cowboys" },
  { value: "crafting", label: "Crafting" },
  { value: "cricket", label: "Cricket" },
  { value: "crime", label: "Crime" },
  { value: "crocodiles", label: "Crocodiles" },
  { value: "curling", label: "Curling" },
  { value: "curses", label: "Curses" },
  { value: "cyberpunk", label: "Cyberpunk" },
  { value: "cyberspace", label: "Cyberspace" },
  { value: "cyborgs", label: "Cyborgs" },
  { value: "dancing", label: "Dancing" },
  { value: "darts", label: "Darts" },
  { value: "dating", label: "Dating" },
  { value: "deck building", label: "Deck Building" },
  { value: "demons", label: "Demons" },
  { value: "desert", label: "Desert" },
  { value: "detective", label: "Detective" },
  { value: "devils", label: "Devils" },
  { value: "dice games", label: "Dice Games" },
  { value: "dieselpunk", label: "Dieselpunk" },
  { value: "digging", label: "Digging" },
  { value: "dinosaurs", label: "Dinosaurs" },
  { value: "diplomacy", label: "Diplomacy" },
  { value: "diving", label: "Diving" },
  { value: "doctors", label: "Doctors" },
  { value: "dogs", label: "Dogs" },
  { value: "dolls", label: "Dolls" },
  { value: "dolphins", label: "Dolphins" },
  { value: "dragons", label: "Dragons" },
  { value: "drawing", label: "Drawing" },
  { value: "dreams", label: "Dreams" },
  { value: "drones", label: "Drones" },
  { value: "druids", label: "Druids" },
  { value: "dungeons", label: "Dungeons" },
  { value: "dwarfs", label: "Dwarfs" },
  { value: "economy", label: "Economy" },
  { value: "education", label: "Education" },
  { value: "elements", label: "Elements" },
  { value: "elves", label: "Elves" },
  { value: "end times", label: "End Times" },
  { value: "erotica", label: "Erotica" },
  { value: "espionage", label: "Espionage" },
  { value: "everyday life", label: "Everyday Life" },
  { value: "evolution", label: "Evolution" },
  { value: "expeditions", label: "Expeditions" },
  { value: "extreme sports", label: "Extreme Sports" },
  { value: "factories", label: "Factories" },
  { value: "fairies", label: "Fairies" },
  { value: "fantasy", label: "Fantasy" },
  { value: "fashion", label: "Fashion" },
  { value: "fencing", label: "Fencing" },
  { value: "fire department", label: "Fire Department" },
  { value: "fish", label: "Fish" },
  { value: "fishing", label: "Fishing" },
  { value: "fitness", label: "Fitness" },
  { value: "food", label: "Food" },
  { value: "frogs", label: "Frogs" },
  { value: "fruit", label: "Fruit" },
  { value: "gambling", label: "Gambling" },
  { value: "game development", label: "Game Development" },
  { value: "gangsters", label: "Gangsters" },
  { value: "genetics", label: "Genetics" },
  { value: "ghosts", label: "Ghosts" },
  { value: "gladiators", label: "Gladiators" },
  { value: "goats", label: "Goats" },
  { value: "goblins", label: "Goblins" },
  { value: "gods", label: "Gods" },
  { value: "golf", label: "Golf" },
  { value: "graveyards", label: "Graveyards" },
  { value: "greek mythology", label: "Greek Mythology" },
  { value: "hacking", label: "Hacking" },
  { value: "handball", label: "Handball" },
  { value: "healthcare", label: "Healthcare" },
  { value: "hedgehogs", label: "Hedgehogs" },
  { value: "helicopters", label: "Helicopters" },
  { value: "hell", label: "Hell" },
  { value: "hiking", label: "Hiking" },
  { value: "historical", label: "Historical" },
  { value: "horror", label: "Horror" },
  { value: "horses", label: "Horses" },
  { value: "hospital", label: "Hospital" },
  { value: "hotels", label: "Hotels" },
  { value: "hunting", label: "Hunting" },
  { value: "ice age", label: "Ice Age" },
  { value: "ice hockey", label: "Ice Hockey" },
  { value: "inca", label: "Inca" },
  { value: "industrialization", label: "Industrialization" },
  { value: "insects", label: "Insects" },
  { value: "islands", label: "Islands" },
  { value: "jet ski", label: "Jet Ski" },
  { value: "jungle", label: "Jungle" },
  { value: "karate", label: "Karate" },
  { value: "kart racing", label: "Kart Racing" },
  { value: "kickboxing", label: "Kickboxing" },
  { value: "kids", label: "Kids" },
  { value: "knights", label: "Knights" },
  { value: "kung fu", label: "Kung Fu" },
  { value: "labyrinth", label: "Labyrinth" },
  { value: "languages", label: "Languages" },
  { value: "learning", label: "Learning" },
  { value: "machines", label: "Machines" },
  { value: "mafia", label: "Mafia" },
  { value: "magic", label: "Magic" },
  { value: "makeup", label: "Makeup" },
  { value: "martial arts", label: "Martial Arts" },
  { value: "mathematics", label: "Mathematics" },
  { value: "mecha", label: "Mecha" },
  { value: "mercenary", label: "Mercenary" },
  { value: "mermaids", label: "Mermaids" },
  { value: "middle ages", label: "Middle Ages" },
  { value: "military", label: "Military" },
  { value: "mining", label: "Mining" },
  { value: "monkeys", label: "Monkeys" },
  { value: "monster", label: "Monster" },
  { value: "motorcycles", label: "Motorcycles" },
  { value: "motorsports", label: "Motorsports" },
  { value: "mountaineering", label: "Mountaineering" },
  { value: "movies", label: "Movies" },
  { value: "mummies", label: "Mummies" },
  { value: "mushrooms", label: "Mushrooms" },
  { value: "music", label: "Music" },
  { value: "musical instrument", label: "Musical Instrument" },
  { value: "mutants", label: "Mutants" },
  { value: "nature", label: "Nature" },
  { value: "ninja", label: "Ninja" },
  { value: "noble houses", label: "Noble Houses" },
  { value: "oceans", label: "Oceans" },
  { value: "octopus", label: "Octopus" },
  { value: "orcs", label: "Orcs" },
  { value: "paintball", label: "Paintball" },
  { value: "parallel worlds", label: "Parallel Worlds" },
  { value: "parkour", label: "Parkour" },
  { value: "parlor games", label: "Parlor Games" },
  { value: "parties", label: "Parties" },
  { value: "pharaohs", label: "Pharaohs" },
  { value: "photography", label: "Photography" },
  { value: "physics", label: "Physics" },
  { value: "pinball", label: "Pinball" },
  { value: "pirates", label: "Pirates" },
  { value: "planets", label: "Planets" },
  { value: "plants", label: "Plants" },
  { value: "playing cards", label: "Playing Cards" },
  { value: "plumber", label: "Plumber" },
  { value: "police", label: "Police" },
  { value: "politics", label: "Politics" },
  { value: "portals", label: "Portals" },
  { value: "predators", label: "Predators" },
  { value: "prison", label: "Prison" },
  { value: "puzzles", label: "Puzzles" },
  { value: "quiz show", label: "Quiz Show" },
  { value: "rabbits", label: "Rabbits" },
  { value: "radioactivity", label: "Radioactivity" },
  { value: "rallycross", label: "Rallycross" },
  { value: "raw materials", label: "Raw Materials" },
  { value: "recycling", label: "Recycling" },
  { value: "religion", label: "Religion" },
  { value: "renovation", label: "Renovation" },
  { value: "reporters", label: "Reporters" },
  { value: "restaurants", label: "Restaurants" },
  { value: "revolution", label: "Revolution" },
  { value: "riding", label: "Riding" },
  { value: "robots", label: "Robots" },
  { value: "rockstars", label: "Rockstars" },
  { value: "roman empire", label: "Roman Empire" },
  { value: "romance", label: "Romance" },
  { value: "romans", label: "Romans" },
  { value: "rugby", label: "Rugby" },
  { value: "saboteurs", label: "Saboteurs" },
  { value: "sailing", label: "Sailing" },
  { value: "samurai", label: "Samurai" },
  { value: "sandbox", label: "Sandbox" },
  { value: "school", label: "School" },
  { value: "science", label: "Science" },
  { value: "secret society", label: "Secret Society" },
  { value: "sewers", label: "Sewers" },
  { value: "sheep", label: "Sheep" },
  { value: "ships", label: "Ships" },
  { value: "showbiz", label: "Showbiz" },
  { value: "singing", label: "Singing" },
  { value: "skateboards", label: "Skateboards" },
  { value: "skeletons", label: "Skeletons" },
  { value: "skiing", label: "Skiing" },
  { value: "skydiving", label: "Skydiving" },
  { value: "snowboarding", label: "Snowboarding" },
  { value: "soccer", label: "Soccer" },
  { value: "space", label: "Space" },
  { value: "space stations", label: "Space Stations" },
  { value: "spaceships", label: "Spaceships" },
  { value: "special forces", label: "Special Forces" },
  { value: "spiders", label: "Spiders" },
  { value: "sports", label: "Sports" },
  { value: "squash", label: "Squash" },
  { value: "squirrels", label: "Squirrels" },
  { value: "steampunk", label: "Steampunk" },
  { value: "stock car", label: "Stock Car" },
  { value: "stock exchanges", label: "Stock Exchanges" },
  { value: "stone age", label: "Stone Age" },
  { value: "stones", label: "Stones" },
  { value: "stuffed animals", label: "Stuffed Animals" },
  { value: "submarines", label: "Submarines" },
  { value: "super villains", label: "Super Villains" },
  { value: "superheroes", label: "Superheroes" },
  { value: "surfing", label: "Surfing" },
  { value: "survivalism", label: "Survivalism" },
  { value: "swimming", label: "Swimming" },
  { value: "table tennis", label: "Table Tennis" },
  { value: "tanks", label: "Tanks" },
  { value: "television", label: "Television" },
  { value: "tennis", label: "Tennis" },
  { value: "terraforming", label: "Terraforming" },
  { value: "theme parks", label: "Theme Parks" },
  { value: "thieves", label: "Thieves" },
  { value: "time travel", label: "Time Travel" },
  { value: "tourism", label: "Tourism" },
  { value: "toys", label: "Toys" },
  { value: "trains", label: "Trains" },
  { value: "transportation", label: "Transportation" },
  { value: "treasure", label: "Treasure" },
  { value: "treasure hunters", label: "Treasure Hunters" },
  { value: "trolls", label: "Trolls" },
  { value: "trucks", label: "Trucks" },
  { value: "tubes", label: "Tubes" },
  { value: "ufos", label: "UFOs" },
  { value: "university", label: "University" },
  { value: "vacation", label: "Vacation" },
  { value: "vampires", label: "Vampires" },
  { value: "victorian age", label: "Victorian Age" },
  { value: "vikings", label: "Vikings" },
  { value: "villages", label: "Villages" },
  { value: "viruses", label: "Viruses" },
  { value: "viticulture", label: "Viticulture" },
  { value: "volleyball", label: "Volleyball" },
  { value: "werewolves", label: "Werewolves" },
  { value: "wild west", label: "Wild West" },
  { value: "witches", label: "Witches" },
  { value: "wizards", label: "Wizards" },
  { value: "world wars", label: "World Wars" },
  { value: "worms", label: "Worms" },
  { value: "wrestling", label: "Wrestling" },
  { value: "yakuza", label: "Yakuza" },
  { value: "zeppelins", label: "Zeppelins" },
  { value: "zombies", label: "Zombies" },
  { value: "zoo", label: "Zoo" },
  { value: "pets", label: "Pets" },
];
